# Continue Pretraining Configuration - FoNE Model
# Loads from: Onlydrinkwater/fone-1p5b-step-76294
# Continues training on MegaMath-web-pro

model_name_or_path: Onlydrinkwater/fone-1p5b-step-76294
data_config: data_megamath.json

# FoNE freezing (preserve number embeddings)
fone_hi: 999  # Freeze embeddings for numbers 0-999
# no_freeze_fone: false  # Set to true to allow number embeddings to update

# Training hyperparameters (lower LR for continue pretrain)
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
warmup_steps: 500
weight_decay: 0.1
log_every_steps: 10

# Distributed training
num_processes: 8
mixed_precision: bf16
dataloader_num_workers: 0

# Wandb logging
wandb_project: fone-continue-pretrain
wandb_run_name: fone_1p5b_megamath_freeze

# HuggingFace upload (final checkpoint only)
hf_repo_id: Onlydrinkwater/fone-1p5b-megamath-freeze

